// <auto-generated />
using System;
using DemoImportExport.Persistents;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoImportExport.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250504072421_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DemoImportExport.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            DepartmentName = "Phòng Kỹ thuật phần mềm"
                        },
                        new
                        {
                            DepartmentId = 2,
                            DepartmentName = "Phòng Nhân sự"
                        },
                        new
                        {
                            DepartmentId = 3,
                            DepartmentName = "Phòng Kế toán"
                        });
                });

            modelBuilder.Entity("DemoImportExport.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankAccount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Branch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("IDNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IssuedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LandlinePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobilePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<int>("TotalRecord")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PositionId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Address = "Hà Nội",
                            BankAccount = "123456789",
                            BankName = "Vietcombank",
                            Branch = "Hà Nội",
                            DOB = new DateTime(1990, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "nva@example.com",
                            EmployeeCode = "NV001",
                            EmployeeName = "Nguyễn Văn A",
                            Gender = 0,
                            IDNo = "123456789",
                            IssueDate = new DateTime(2010, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IssuedBy = "Công an Hà Nội",
                            LandlinePhone = "0241234567",
                            MobilePhone = "0912345678",
                            Password = "123@abc",
                            PositionId = 1,
                            TotalRecord = 10
                        },
                        new
                        {
                            EmployeeId = 2,
                            Address = "TP HCM",
                            BankAccount = "987654321",
                            BankName = "ACB",
                            Branch = "TP HCM",
                            DOB = new DateTime(1985, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "ttb@example.com",
                            EmployeeCode = "NV002",
                            EmployeeName = "Trần Thị B",
                            Gender = 1,
                            IDNo = "987654321",
                            IssueDate = new DateTime(2005, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IssuedBy = "Công an TP HCM",
                            LandlinePhone = "0281234567",
                            MobilePhone = "0909123456",
                            Password = "456@def",
                            PositionId = 2,
                            TotalRecord = 12
                        },
                        new
                        {
                            EmployeeId = 3,
                            Address = "Đà Nẵng",
                            BankAccount = "111222333",
                            BankName = "BIDV",
                            Branch = "Đà Nẵng",
                            DOB = new DateTime(1992, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "lvc@example.com",
                            EmployeeCode = "NV003",
                            EmployeeName = "Lê Văn C",
                            Gender = 0,
                            IDNo = "111222333",
                            IssueDate = new DateTime(2012, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IssuedBy = "Công an Đà Nẵng",
                            LandlinePhone = "0236123456",
                            MobilePhone = "0938123456",
                            Password = "789@ghi",
                            PositionId = 3,
                            TotalRecord = 8
                        });
                });

            modelBuilder.Entity("DemoImportExport.Models.Position", b =>
                {
                    b.Property<int>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PositionId"));

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("PositionId");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            PositionId = 1,
                            PositionName = "Lập trình viên"
                        },
                        new
                        {
                            PositionId = 2,
                            PositionName = "Trưởng phòng"
                        },
                        new
                        {
                            PositionId = 3,
                            PositionName = "Kế toán viên"
                        });
                });

            modelBuilder.Entity("DemoImportExport.Models.Employee", b =>
                {
                    b.HasOne("DemoImportExport.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DemoImportExport.Models.Position", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("DemoImportExport.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("DemoImportExport.Models.Position", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
